language: ruby
rvm:
  - 2.2.1
env:
  - DB=postgresql  
gemfile:
  - Gemfile
addons:
  postgresql: "9.3"  
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database source_test;' -U postgres