# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

jan = User.create!(name: "jan", email: "jan@email.com", password: "123")
blanche = User.create!(name: "blanche", email: "blanche@email.com", password: "123")
rose = User.create!(name: "rose", email: "rose@email.com", password: "123")
chad = User.create!(name: "chad", email: "chad@email.com", password: "123")

q1 = Question.create!(title: "Mrs. Robinson, you're trying to seduce me. Aren't you?", body: "Master cleanse Etsy mixtape, roof party small batch fashion axe fap heirloom mlkshk semiotics deep v Odd Future gluten-free keytar Banksy. PBR&B keffiyeh pug Wes Anderson, pop-up keytar freegan McSweeney's biodiesel Intelligentsia. Distillery DIY Williamsburg pug pop-up, asymmetrical messenger bag gastropub swag VHS narwhal trust fund vegan crucifix direct trade. Tousled vegan Wes Anderson, DIY sartorial meggings Shoreditch disrupt aesthetic Pitchfork keffiyeh wayfarers cred. Tumblr ethical next level McSweeney's, Thundercats bicycle rights Intelligentsia quinoa heirloom meggings. Portland meditation typewriter taxidermy cray cliche. Small batch Godard occupy, sriracha Banksy tote bag Tumblr.", user: jan)
q2 = Question.create!(title: "Hey Dad. You wanna have a catch?", body: "Banksy PBR&B cornhole American Apparel trust fund swag butcher, letterpress sriracha single-origin coffee stumptown cronut heirloom farm-to-table Portland. You probably haven't heard of them Kickstarter flannel, lo-fi 3 wolf moon messenger bag gastropub scenester Tumblr listicle cred. Fixie beard bicycle rights tote bag McSweeney's farm-to-table, cray Pinterest listicle bitters chia biodiesel 3 wolf moon. Disrupt vegan bitters banh mi Brooklyn direct trade. You probably haven't heard of them Vice fingerstache, bitters pickled migas narwhal artisan sriracha Banksy tattooed four loko gastropub asymmetrical wolf. Deep v small batch fixie iPhone, meh aesthetic listicle. Etsy tofu 8-bit wolf, selfies four loko hoodie you probably haven't heard of them ethical fixie kitsch fanny pack street art squid lo-fi.", user: blanche)
q3 = Question.create!(title: "Aren’t you a little short for a stormtrooper?", body: "8-bit chia banjo, Marfa cardigan chillwave slow-carb Shoreditch put a bird on it food truck tattooed single-origin coffee. Butcher farm-to-table Vice, polaroid whatever messenger bag flexitarian slow-carb Marfa. Retro quinoa mustache +1 hashtag. Four loko blog quinoa church-key. Quinoa Portland whatever, pour-over Williamsburg put a bird on it Banksy locavore umami lo-fi plaid pop-up fixie Brooklyn food truck. Thundercats authentic craft beer letterpress, meggings selvage Truffaut Pitchfork Vice four loko Austin food truck. DIY pour-over High Life food truck authentic drinking vinegar.", user: rose)
q4 = Question.create!(title: "Shall we play a game?", body: "Godard fap trust fund, vinyl Banksy Echo Park locavore Pinterest. Paleo blog food truck, street art PBR Marfa aesthetic normcore bitters craft beer leggings taxidermy 90's. Austin health goth organic, food truck swag flannel Carles Banksy VHS. Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.", user: chad)
q5 = Question.create!(title: "You've gotta ask yourself a question: 'Do I feel lucky?' Well, do ya, punk?", body: "Heirloom drinking vinegar whatever, semiotics wolf meh hella plaid Intelligentsia letterpress cred street art 90's leggings 3 wolf moon. Beard skateboard bicycle rights, freegan crucifix deep v small batch vegan disrupt craft beer meditation. Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie. DIY post-ironic squid meditation cronut chambray. Sartorial lomo Etsy, pork belly cred occupy four loko tofu. Irony meditation seitan chillwave hoodie.", user: rose)

a1 = Answer.create!(question: q1, user: blanche, body: "Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie.")
a2 = Answer.create!(question: q2, user: jan, body: "Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie. DIY post-ironic squid meditation cronut chambray. Sartorial lomo Etsy, pork belly cred occupy four loko tofu. Irony meditation seitan chillwave hoodie.")
a3 = Answer.create!(question: q3, user: blanche, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a4 = Answer.create!(question: q2, user: blanche, body: "Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie.")
a5 = Answer.create!(question: q1, user: jan, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a6 = Answer.create!(question: q4, user: rose, body: "Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie.")
a7 = Answer.create!(question: q5, user: chad, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a8 = Answer.create!(question: q2, user: jan, body: "Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie. DIY post-ironic squid meditation cronut chambray. Sartorial lomo Etsy, pork belly cred occupy four loko tofu. Irony meditation seitan chillwave hoodie.")
a9 = Answer.create!(question: q3, user: chad, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a10 = Answer.create!(question: q4, user: blanche, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a11 = Answer.create!(question: q5, user: jan, body: "Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie.")
a12 = Answer.create!(question: q2, user: rose, body: "Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie. DIY post-ironic squid meditation cronut chambray. Sartorial lomo Etsy, pork belly cred occupy four loko tofu. Irony meditation seitan chillwave hoodie.")
a13 = Answer.create!(question: q1, user: jan, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
a14 = Answer.create!(question: q3, user: rose, body: "Chia bicycle rights umami mustache irony. Paleo cardigan Williamsburg flexitarian migas cornhole heirloom, authentic hoodie.")
a15 = Answer.create!(question: q4, user: jan, body: "Cred normcore literally, gentrify shabby chic chillwave synth McSweeney's Kickstarter freegan pour-over wayfarers pug. Typewriter Etsy pour-over, quinoa banh mi meggings cornhole leggings sriracha Thundercats jean shorts. Tumblr taxidermy Truffaut mustache wolf VHS. Cornhole hella cliche meh.")
